#!/usr/bin/env python

import pytest
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel

from easy_agents.agents.code.symbol_analyzer import SymbolAnalysis, SymbolAnalysisRequest, symbol_analyzer
from easy_agents.core import Router, ToolDepsRegistry
from easy_agents.tools.deps.project_files_deps import ProjectFilesDeps, project_files_deps_type


def print_symbol_analysis(analysis: SymbolAnalysis):
    """
    Converts SymbolAnalysis to a rich Markdown format and prints it.
    """
    console = Console()

    # 1. Build the Markdown String
    md_content = f"""# 🔍 Symbol Analysis: `{analysis.symbol_name}`
**Type:** `{analysis.type}`

---

## 📝 Brief
{analysis.brief}

## 📖 Detailed Analysis
{analysis.details}

---

## 🚀 Use Cases
{chr(10).join([f"* 💡 {uc}" for uc in analysis.use_cases])}

---

## ⚠️ Potential Edge Cases
{chr(10).join([f"* 🚩 {ec}" for ec in analysis.edge_cases])}

---

## 🔗 Related Symbols
| Symbol Group | Description / Relation |
| :--- | :--- |
{chr(10).join([f"| **{key}** | {val} |" for key, val in analysis.related_symbols.items()])}

---
*Analysis generated by Symbol Analyzer Agent*
    """

    # 2. Render using Rich
    # We wrap it in a Panel for a cleaner "UI" feel in the console
    markdown = Markdown(md_content)

    console.print(
        Panel(
            markdown,
            border_style="bright_blue",
            expand=False,
            title=f"Analysis of [bold]{analysis.symbol_name}[/bold]",
            subtitle="[italic]Developer Intelligence Report[/italic]",
        )
    )


@pytest.mark.asyncio
async def test_agent(simple_router: Router, pytestconfig: pytest.Config) -> None:
    result = await symbol_analyzer.run(
        SymbolAnalysisRequest(symbol_name="Agent"),
        simple_router,
        deps=ToolDepsRegistry.from_map(
            {project_files_deps_type: ProjectFilesDeps(project_root=str(pytestconfig.rootpath))}
        ),
    )
    print(result.model_dump_json())
    print_symbol_analysis(result)
